export const SAMPLE_CARDS = [
    {
        id: "https://optcgapi.com/media/static/Card_Images/OP01-077.jpg",
        setId: "OP-01",
        setName: "Romance Dawn",
        cardSetId: "OP01-077",
        name: "Perona",
        imageUrl: "https://optcgapi.com/media/static/Card_Images/OP01-077.jpg",
        marketPrice: 0.64,
        rarity: "UC",
        color: "Blue",
        type: "Character",
        cost: "1",
        power: "2000",
        life: null,
        counter: 1000,
        attribute: "Special",
        subTypes: ["Thriller Bark Pirates"],
        text: "[On Play] Look at 5 cards from the top of your deck and place them at the top or bottom of the deck in any order.",
        scrapedAt: "2026-04-22"
    },
    {
        id: "https://optcgapi.com/media/static/Card_Images/OP01-025.jpg",
        setId: "OP-01",
        setName: "Romance Dawn",
        cardSetId: "OP01-025",
        name: "Roronoa Zoro",
        imageUrl: "https://optcgapi.com/media/static/Card_Images/OP01-025.jpg",
        marketPrice: 18.5,
        rarity: "SR",
        color: "Red",
        type: "Character",
        cost: "3",
        power: "5000",
        life: null,
        counter: 1000,
        attribute: "Slash",
        subTypes: ["Straw Hat Crew", "Supernovas"],
        text: "[DON!! x1] This Character gains +1000 power.",
        scrapedAt: "2026-04-22"
    },
    {
        id: "https://optcgapi.com/media/static/Card_Images/OP01-001.jpg",
        setId: "OP-01",
        setName: "Romance Dawn",
        cardSetId: "OP01-001",
        name: "Monkey.D.Luffy",
        imageUrl: "https://optcgapi.com/media/static/Card_Images/OP01-001.jpg",
        marketPrice: 3.21,
        rarity: "L",
        color: "Red",
        type: "Leader",
        cost: null,
        power: "5000",
        life: "5",
        counter: null,
        attribute: "Strike",
        subTypes: ["Straw Hat Crew"],
        text: "[Activate: Main] [Once Per Turn] Give 1 rested DON!! card to 1 of your Characters.",
        scrapedAt: "2026-04-22"
    },
    {
        id: "https://optcgapi.com/media/static/Card_Images/OP02-004.jpg",
        setId: "OP-02",
        setName: "Paramount War",
        cardSetId: "OP02-004",
        name: "Edward.Newgate",
        imageUrl: "https://optcgapi.com/media/static/Card_Images/OP02-004.jpg",
        marketPrice: 9.95,
        rarity: "L",
        color: "Red",
        type: "Leader",
        cost: null,
        power: "6000",
        life: "6",
        counter: null,
        attribute: "Special",
        subTypes: ["Whitebeard Pirates"],
        text: "[End of Your Turn] Add 1 card from the top of your Life cards to your hand.",
        scrapedAt: "2026-04-22"
    },
    {
        id: "https://optcgapi.com/media/static/Card_Images/OP02-099.jpg",
        setId: "OP-02",
        setName: "Paramount War",
        cardSetId: "OP02-099",
        name: "Sakazuki",
        imageUrl: "https://optcgapi.com/media/static/Card_Images/OP02-099.jpg",
        marketPrice: 2.47,
        rarity: "R",
        color: "Black",
        type: "Character",
        cost: "5",
        power: "6000",
        life: null,
        counter: 1000,
        attribute: "Special",
        subTypes: ["Navy"],
        text: "[On Play] K.O. up to 1 of your opponent's Characters with a cost of 2 or less.",
        scrapedAt: "2026-04-22"
    },
    {
        id: "https://optcgapi.com/media/static/Card_Images/OP03-040.jpg",
        setId: "OP-03",
        setName: "Pillars of Strength",
        cardSetId: "OP03-040",
        name: "Charlotte Katakuri",
        imageUrl: "https://optcgapi.com/media/static/Card_Images/OP03-040.jpg",
        marketPrice: 11.2,
        rarity: "SR",
        color: "Yellow",
        type: "Character",
        cost: "8",
        power: "8000",
        life: null,
        counter: null,
        attribute: "Strike",
        subTypes: ["Big Mom Pirates"],
        text: "[On Play] Place up to 1 card from the top of your opponent's Life cards on the top or bottom of the owner's deck.",
        scrapedAt: "2026-04-22"
    }
];

const KNOWN_SETS = [
    { set_name: "Romance Dawn", set_id: "OP-01" },
    { set_name: "Paramount War", set_id: "OP-02" },
    { set_name: "Pillars of Strength", set_id: "OP-03" },
    { set_name: "Kingdoms of Intrigue", set_id: "OP-04" },
    { set_name: "Awakening of the New Era", set_id: "OP-05" },
    { set_name: "Wings of the Captain", set_id: "OP-06" },
    { set_name: "500 Years in the Future", set_id: "OP-07" },
    { set_name: "Extra Booster: Memorial Collection", set_id: "EB-01" },
    { set_name: "Two Legends", set_id: "OP-08" },
    { set_name: "Emperors in the New World", set_id: "OP-09" },
    { set_name: "Royal Blood", set_id: "OP-10" },
    { set_name: "A Fist of Divine Speed", set_id: "OP-11" },
    { set_name: "Extra Booster: Anime 25th Collection", set_id: "EB-02" },
    { set_name: "Legacy of the Master", set_id: "OP-12" },
    { set_name: "Premium Booster - The Best", set_id: "PRB-01" },
    { set_name: "Premium Booster - The Best - Vol. 2", set_id: "PRB-02" },
    { set_name: "Carrying On His Will", set_id: "OP-13" },
    { set_name: "The Azure Sea's Seven", set_id: "OP14-EB04" },
    { set_name: "Extra Booster: One Piece Heroines Edition", set_id: "EB-03" },
    { set_name: "Adventure on Kami's Island", set_id: "OP15-EB04" }
];

export const SAMPLE_SETS = KNOWN_SETS.map(({ set_id, set_name }) => ({
    id: set_id,
    name: set_name,
    code: set_id,
    cardCount: SAMPLE_CARDS.filter((card) => card.setId === set_id).length
}));
