import type { CardRecord, SetRecord } from "./types";

export const SAMPLE_CARDS: CardRecord[] = [
  {
    id: "OP01-077",
    setId: "OP-01",
    setName: "Romance Dawn",
    cardSetId: "OP01-077",
    name: "Perona",
    imageUrl: "https://optcgapi.com/media/static/Card_Images/OP01-077.jpg",
    marketPrice: 0.64,
    rarity: "UC",
    color: "Blue",
    type: "Character",
    cost: "1",
    power: "2000",
    life: null,
    counter: 1000,
    attribute: "Special",
    subTypes: ["Thriller Bark Pirates"],
    text: "[On Play] Look at 5 cards from the top of your deck and place them at the top or bottom of the deck in any order.",
    scrapedAt: "2026-04-22",
  },
  {
    id: "OP01-025",
    setId: "OP-01",
    setName: "Romance Dawn",
    cardSetId: "OP01-025",
    name: "Roronoa Zoro",
    imageUrl: "https://optcgapi.com/media/static/Card_Images/OP01-025.jpg",
    marketPrice: 18.5,
    rarity: "SR",
    color: "Red",
    type: "Character",
    cost: "3",
    power: "5000",
    life: null,
    counter: 1000,
    attribute: "Slash",
    subTypes: ["Straw Hat Crew", "Supernovas"],
    text: "[DON!! x1] This Character gains +1000 power.",
    scrapedAt: "2026-04-22",
  },
  {
    id: "OP01-001",
    setId: "OP-01",
    setName: "Romance Dawn",
    cardSetId: "OP01-001",
    name: "Monkey.D.Luffy",
    imageUrl: "https://optcgapi.com/media/static/Card_Images/OP01-001.jpg",
    marketPrice: 3.21,
    rarity: "L",
    color: "Red",
    type: "Leader",
    cost: null,
    power: "5000",
    life: "5",
    counter: null,
    attribute: "Strike",
    subTypes: ["Straw Hat Crew"],
    text: "[Activate: Main] [Once Per Turn] Give 1 rested DON!! card to 1 of your Characters.",
    scrapedAt: "2026-04-22",
  },
  {
    id: "OP02-004",
    setId: "OP-02",
    setName: "Paramount War",
    cardSetId: "OP02-004",
    name: "Edward.Newgate",
    imageUrl: "https://optcgapi.com/media/static/Card_Images/OP02-004.jpg",
    marketPrice: 9.95,
    rarity: "L",
    color: "Red",
    type: "Leader",
    cost: null,
    power: "6000",
    life: "6",
    counter: null,
    attribute: "Special",
    subTypes: ["Whitebeard Pirates"],
    text: "[End of Your Turn] Add 1 card from the top of your Life cards to your hand.",
    scrapedAt: "2026-04-22",
  },
  {
    id: "OP02-099",
    setId: "OP-02",
    setName: "Paramount War",
    cardSetId: "OP02-099",
    name: "Sakazuki",
    imageUrl: "https://optcgapi.com/media/static/Card_Images/OP02-099.jpg",
    marketPrice: 2.47,
    rarity: "R",
    color: "Black",
    type: "Character",
    cost: "5",
    power: "6000",
    life: null,
    counter: 1000,
    attribute: "Special",
    subTypes: ["Navy"],
    text: "[On Play] K.O. up to 1 of your opponent's Characters with a cost of 2 or less.",
    scrapedAt: "2026-04-22",
  },
  {
    id: "OP03-040",
    setId: "OP-03",
    setName: "Pillars of Strength",
    cardSetId: "OP03-040",
    name: "Charlotte Katakuri",
    imageUrl: "https://optcgapi.com/media/static/Card_Images/OP03-040.jpg",
    marketPrice: 11.2,
    rarity: "SR",
    color: "Yellow",
    type: "Character",
    cost: "8",
    power: "8000",
    life: null,
    counter: null,
    attribute: "Strike",
    subTypes: ["Big Mom Pirates"],
    text: "[On Play] Place up to 1 card from the top of your opponent's Life cards on the top or bottom of the owner's deck.",
    scrapedAt: "2026-04-22",
  },
];

export const SAMPLE_SETS: SetRecord[] = [
  {
    id: "OP-01",
    name: "Romance Dawn",
    code: "OP-01",
    cardCount: SAMPLE_CARDS.filter((card) => card.setId === "OP-01").length,
  },
  {
    id: "OP-02",
    name: "Paramount War",
    code: "OP-02",
    cardCount: SAMPLE_CARDS.filter((card) => card.setId === "OP-02").length,
  },
  {
    id: "OP-03",
    name: "Pillars of Strength",
    code: "OP-03",
    cardCount: SAMPLE_CARDS.filter((card) => card.setId === "OP-03").length,
  },
];
